# Generated by Django 4.0.4 on 2023-06-21 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('age_classification', models.CharField(choices=[('ATP', 'Apta para Todo Publico'), ('+13', 'Sólo apta para mayores de 13 años'), ('+16', 'Sólo apta para mayores de 16 años'), ('+18', 'Sólo apta para mayores de 18 años'), ('C', 'Sólo apta para mayores de 18 años exhibición condicionada')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mayores', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menores', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(default=datetime.datetime(2023, 6, 21, 20, 37, 54, 728411, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Sala 1'), ('2', 'Sala 2'), ('3', 'Sala 3')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asientos_ocupados', models.JSONField(default=dict)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.pelicula')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.precio')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entradas_menores', models.IntegerField()),
                ('entradas_mayores', models.IntegerField()),
                ('asientos', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.funcion')),
            ],
        ),
    ]
