# Generated by Django 4.0.4 on 2023-06-21 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
