# Generated by Django 4.0.4 on 2023-06-21 21:59

from django.db import migrations, models
import vendedor.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_alter_funcion_asientos_ocupados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='asientos_ocupados',
            field=models.JSONField(default=vendedor.models.sala_vacia),
        ),
    ]
