# Generated by Django 4.0.4 on 2023-06-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_alter_funcion_asientos_ocupados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(default='Español', max_length=20),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='subtitulos',
            field=models.BooleanField(default=False),
        ),
    ]
