# Generated by Django 4.0.4 on 2023-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0005_pelicula_idioma_pelicula_subtitulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(choices=[('Es', 'Español'), ('En', 'Ingles'), ('Pr', 'Portugues')], default='Es', max_length=20),
        ),
    ]
