# Generated by Django 4.2.2 on 2023-06-23 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0006_alter_pelicula_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='publicadora',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
