# Generated by Django 4.2.2 on 2023-06-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0007_pelicula_cartel_pelicula_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(default='static/images/no-image.png', upload_to='images/'),
        ),
    ]
