# Generated by Django 4.2.2 on 2023-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0008_alter_pelicula_cartel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
