# Generated by Django 4.2.2 on 2023-06-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0009_alter_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(default='static/images/no-image.png', upload_to='static/images/'),
        ),
    ]
